services:
  backend:
    build: ./backend
    container_name: flask-backend
    environment:
      - DB_HOST=db
      - DB_NAME=myapp
      - DB_USER=admin
      - DB_PASSWORD=secret123
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: flask-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRESS_DB: myapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: flask-redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: flask-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
